version: '3.8'

services:
  pelv-primary-service:
    build:
      context: ./pelv-primary-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    networks:
      - pelv-network

networks:
  pelv-network:
    driver: bridge