openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: This is an example API

paths:
  /login:
    post:
      summary: Login user
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "your_jwt_token"

  /welcome:
    get:
      summary: Welcome
      operationId: welcome
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome user"

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
